In [1]:
import tensorflow as tf
import numpy as np

### Tf의 dimmention 대응 

In [7]:
# with tf.Session() as sess:
#     a = tf.constant([1.0,2.0]
#                     ,[3.0,4.0])
#     print(a)
#     print(sess.run(a))

with tf.Session() as sess:
    a = tf.constant([1.0,2.0,3.0,4.0], shape=[2,2])
    print(a)
    print(sess.run(a))
    

Tensor("Const_2:0", shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]


### Numpy 사용하기

In [11]:
with tf.Session() as sess:
    a = tf.constant([1.0,2.0,3.0,4.0], shape=[2,2])
    b = a+1 
    print(a)
    print(b)
    c = a*b
    # numpy 에서 사용하는 연산과 같이 지원됨
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(tf.matmul(a,b)))

Tensor("Const_6:0", shape=(2, 2), dtype=float32)
Tensor("add_3:0", shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]
[[2. 3.]
 [4. 5.]]
[[10. 13.]
 [22. 29.]]


### tf.Varaible - Variable shoude be  ini

- variable 은 미분을하기 위한 값이 추가로 있음으로 반드시 초기화 되어야한다.

In [16]:
x = tf.Variable(1.0)
with tf.Session() as sess:
    # 방법 1 변수의 initializer
#     print(x.initializer)
    sess.run(x.initializer)
    print(sess.run(x))

1.0


In [19]:
x = tf.Variable(1.0)
# 방법 2 모든 변수의 초기화 
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))

1.0


### gpu cpu performance 비교

- Cpu 와 Gpu 성능 비교 하기!

In [27]:
import time

def measuere(x,steps):
    with tf.Session() as sess:
        # 초기화시 gpu 속도가 느려지는 시간을 제외하기 위해서 
        sess.run(tf.matmul(x,x))
        start = time.time()
        for i in range(steps):
            x = tf.matmul(x,x)
        _ = sess.run(x)
        end = time.time()
        sess.close()
    return end - start

In [28]:
# 장비 선택및 비교하기
shape = (10000,10000)
steps = 2
with tf.device("/cpu:0"):
    print("CPU : {} secs".format(measuere(tf.random_normal(shape),steps)))

if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        print("GPU : {} secs".format(measuere(tf.random_normal(shape),steps)))
else:
    print("GPU not found")

CPU : 16.752376317977905 secs


InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(10000, 10000), b.shape=(10000, 10000), m=10000, n=10000, k=10000
	 [[node MatMul_43 (defined at d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
  (1) Internal: Blas GEMM launch failed : a.shape=(10000, 10000), b.shape=(10000, 10000), m=10000, n=10000, k=10000
	 [[node MatMul_43 (defined at d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	 [[MatMul_43/_1]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'MatMul_43':
  File "d:\tool\conda\envs\skku\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\tool\conda\envs\skku\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\tool\conda\envs\skku\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "d:\tool\conda\envs\skku\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "d:\tool\conda\envs\skku\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "d:\tool\conda\envs\skku\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "d:\tool\conda\envs\skku\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\tool\conda\envs\skku\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\tool\conda\envs\skku\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "d:\tool\conda\envs\skku\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "d:\tool\conda\envs\skku\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "d:\tool\conda\envs\skku\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "d:\tool\conda\envs\skku\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "d:\tool\conda\envs\skku\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-5ebf697b32e7>", line 9, in <module>
    print("GPU : {} secs".format(measuere(tf.random_normal(shape),steps)))
  File "<ipython-input-27-059970d903b8>", line 6, in measuere
    sess.run(tf.matmul(x,x))
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 2754, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 6136, in mat_mul
    name=name)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "d:\tool\conda\envs\skku\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()


### Computing gradients
- 미분 해보기

In [2]:
x =  tf.constant(3.0)
init = tf.global_variables_initializer()
with tf.GradientTape() as g:
    g.watch(x)
    y = x*x

dy_dx = g.gradient(y,x)

with tf.Session() as sess:
    print(sess.run(dy_dx))


6.0


- 복잡한 연산에서 미분 해보기

In [4]:
x =  tf.constant(3.0)
init = tf.global_variables_initializer()
# 기록
with tf.GradientTape() as g:
    g.watch(x)
    y = 1
    for i in range(3):
        if i < 2:
            y *= x
        else:
            y += x
        # x^2 + x

dy_dx = g.gradient(y,x)

with tf.Session() as sess:
    print(sess.run(dy_dx))


7.0


In [5]:
x =  tf.constant(3.0)
init = tf.global_variables_initializer()
# 기록
with tf.GradientTape() as g:
    g.watch(x)
    y = 1
    with tf.GradientTape() as gg:
        gg.watch(x)
        y = x*x
    dy_dx = gg.gradient(y,x)
dy_dx2 = g.gradient(dy_dx,x)


with tf.Session() as sess:
    print(sess.run(dy_dx))
    print(sess.run(dy_dx2))


6.0
2.0


### 간단한 예제 진행해 보기

In [2]:
# matplotlib 플로팅 도구를 
%matplotlib.inline
import matplotlib.pyplot as plt 

UsageError: Line magic function `%matplotlib.inline` not found.
